//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emaratech.Services.Channels.SSO.ChannelService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestService", Namespace="http://schemas.datacontract.org/2004/07/Emaratech.Services.Channels.Contracts")]
    [System.SerializableAttribute()]
    public partial class RestService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryResourceKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResourceKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCategoryResourceKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIdField, value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryResourceKey {
            get {
                return this.CategoryResourceKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryResourceKeyField, value) != true)) {
                    this.CategoryResourceKeyField = value;
                    this.RaisePropertyChanged("CategoryResourceKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResourceKey {
            get {
                return this.ResourceKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceKeyField, value) != true)) {
                    this.ResourceKeyField = value;
                    this.RaisePropertyChanged("ResourceKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCategoryId {
            get {
                return this.SubCategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCategoryIdField, value) != true)) {
                    this.SubCategoryIdField = value;
                    this.RaisePropertyChanged("SubCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCategoryResourceKey {
            get {
                return this.SubCategoryResourceKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCategoryResourceKeyField, value) != true)) {
                    this.SubCategoryResourceKeyField = value;
                    this.RaisePropertyChanged("SubCategoryResourceKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChannelService.IChannelService")]
    public interface IChannelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorsAwareRestWcfService/OptionsHandler", ReplyAction="http://tempuri.org/ICorsAwareRestWcfService/OptionsHandlerResponse")]
        void OptionsHandler();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorsAwareRestWcfService/OptionsHandler", ReplyAction="http://tempuri.org/ICorsAwareRestWcfService/OptionsHandlerResponse")]
        System.Threading.Tasks.Task OptionsHandlerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelService/GetServices", ReplyAction="http://tempuri.org/IChannelService/GetServicesResponse")]
        Emaratech.Services.Channels.SSO.ChannelService.RestService[] GetServices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelService/GetServices", ReplyAction="http://tempuri.org/IChannelService/GetServicesResponse")]
        System.Threading.Tasks.Task<Emaratech.Services.Channels.SSO.ChannelService.RestService[]> GetServicesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChannelServiceChannel : Emaratech.Services.Channels.SSO.ChannelService.IChannelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChannelServiceClient : System.ServiceModel.ClientBase<Emaratech.Services.Channels.SSO.ChannelService.IChannelService>, Emaratech.Services.Channels.SSO.ChannelService.IChannelService {
        
        public ChannelServiceClient() {
        }
        
        public ChannelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChannelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void OptionsHandler() {
            base.Channel.OptionsHandler();
        }
        
        public System.Threading.Tasks.Task OptionsHandlerAsync() {
            return base.Channel.OptionsHandlerAsync();
        }
        
        public Emaratech.Services.Channels.SSO.ChannelService.RestService[] GetServices() {
            return base.Channel.GetServices();
        }
        
        public System.Threading.Tasks.Task<Emaratech.Services.Channels.SSO.ChannelService.RestService[]> GetServicesAsync() {
            return base.Channel.GetServicesAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChannelService.IUserChannelService")]
    public interface IUserChannelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorsAwareRestWcfService/OptionsHandler", ReplyAction="http://tempuri.org/ICorsAwareRestWcfService/OptionsHandlerResponse")]
        void OptionsHandler();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorsAwareRestWcfService/OptionsHandler", ReplyAction="http://tempuri.org/ICorsAwareRestWcfService/OptionsHandlerResponse")]
        System.Threading.Tasks.Task OptionsHandlerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserChannelService/GetUserId", ReplyAction="http://tempuri.org/IUserChannelService/GetUserIdResponse")]
        string GetUserId(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserChannelService/GetUserId", ReplyAction="http://tempuri.org/IUserChannelService/GetUserIdResponse")]
        System.Threading.Tasks.Task<string> GetUserIdAsync(string login);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserChannelServiceChannel : Emaratech.Services.Channels.SSO.ChannelService.IUserChannelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserChannelServiceClient : System.ServiceModel.ClientBase<Emaratech.Services.Channels.SSO.ChannelService.IUserChannelService>, Emaratech.Services.Channels.SSO.ChannelService.IUserChannelService {
        
        public UserChannelServiceClient() {
        }
        
        public UserChannelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserChannelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserChannelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserChannelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void OptionsHandler() {
            base.Channel.OptionsHandler();
        }
        
        public System.Threading.Tasks.Task OptionsHandlerAsync() {
            return base.Channel.OptionsHandlerAsync();
        }
        
        public string GetUserId(string login) {
            return base.Channel.GetUserId(login);
        }
        
        public System.Threading.Tasks.Task<string> GetUserIdAsync(string login) {
            return base.Channel.GetUserIdAsync(login);
        }
    }
}
