//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emaratech.Services.Channels.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emaratech.Services.Channels.DataAccess.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select s.id from  
        ///                   allow_spn s,client_mast m,client_det d 
        ///                   where m.id = s.grp_id and m.status = 21 and s.user_id =d.ID 
        ///                   and d.id  =  :user_id  
        ///                   and d.user_tp not in (&apos;I&apos;,&apos;G&apos;,&apos;O&apos;,&apos;P&apos;,&apos;C&apos;)          
        ///            union all
        ///            select s.id al_cd from 
        ///                   allow_spn s, client_det d , client_mast m
        ///                   where m.id = d.grp_id and m.status = 21 and d.id = s.user_id 
        ///                   and s.grp_i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GET_ALLOW_SPN_ID {
            get {
                return ResourceManager.GetString("GET_ALLOW_SPN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id from client_det where login = :login.
        /// </summary>
        internal static string GET_USER_ID {
            get {
                return ResourceManager.GetString("GET_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select to_char(a.visa_type_cd) v_cd
        ///             from inimm_db.app_visatypes_vw a,FEE_VISATP F
        ///                  where a.id = :allow_spn_id
        ///                  and a.visa_type_cd not in(select visa_type_cd from inimm_lk.ref_96hourvw) 
        ///                  AND a.visa_type_cd = F.TP_CD.
        /// </summary>
        internal static string GET_VISA_TYPES_FOR_SPN {
            get {
                return ResourceManager.GetString("GET_VISA_TYPES_FOR_SPN", resourceCulture);
            }
        }
    }
}
